### ISSUE TITLE
custom messages

### ISSUE THREAD

**Issue by Londerson** [Resize/Validation#43]
Thinking how user can customize your messages when result is false, i want to try something like this:

```ruby
Resize::Validation::validate(integer: "this is sting", message: "This is not one string")
```

Any idea? @psantos10 @raphaelduartepinheiro  @romulostorel @heliohead @FelipeCaue

**Comment by raphaelduartepinheiro** [comment]
This way as you showed can mess the code with strings, and let user mix code with regional languages. I would suggest change this approach. A YAML file to hold all the messages. If someone wants a custom message, one can modify there.

**Comment by Londerson** [comment]
+1 for your idea. Custom messages is something that was inspired by the Rails, and your api is something like:
```ruby
validates_presence_of :name, :message => "can't be empty" 
```
If we use locales and i18 we can have one .yml file with this errors translated for a lot of languages, and the final user can customize as he wishes.
```yaml
en:
    errors:
      is_integer: "This number is not a valid!"
      is_domain: "This url is not a valid domain!"
pt:
    errors:
      is_integer: "Esse não é um formato válido!"
      is_domain: "Essa URL não é válida!"
```
And if we have this two ways to customize messages, and perhaps prioritizing the value entered in the hash message: "blah" when there is a call to Resize::Validation::validate, mix code with regional languages not seem to be a good idea.

```ruby
validates_presence_of :name, :message => "não é valido" 
```

:/
